"""Operator Library: curated financial operators for alpha construction.

This module defines the symbolic operator set Omega used to construct
formulaic alpha factors. Each operator is a building block that transforms
market data into predictive signals.

All operators below are backed by deterministic pandas/numpy implementations
in `evaluation/evaluator.py::FormulaExecutor`, ensuring that every factor
generated by the LLM can be compiled into rigorous, hallucination-free
vectorised arithmetic.
"""

import dataclasses
import typing


@dataclasses.dataclass
class Operator:
    """Represents a single operator in the library."""
    name: str
    category: str
    signature: str
    description: str
    example: typing.Optional[str] = None


class OperatorLibrary:
    """Curated library of 60+ financial operators.

    Organized into categories:
      - Time-Series (Ts_*)
      - Cross-Sectional (Cs_*)
      - Mathematical
      - Financial (raw fields, matching market-data parquet columns)
      - Logical / Conditional
      - Statistical
    """

    def __init__(self):
        self._operators: typing.List[Operator] = []
        self._build_library()

    def _build_library(self):
        """Populate the library with operators backed by exact formulas."""
        ops = []

        # ============================
        # 1. Time-Series Operators (Ts_*)
        # ============================
        ts_ops = [
            Operator("Ts_Rank", "TimeSeries", "Ts_Rank(x, d, min_periods=1)",
                     "Rank of x over the past d time steps, normalised to [0,1]. "
                     "min_periods: min observations required (default 1). "
                     "Formula: rank(x[t-d+1:t]) / d (ordinal rank within window, pct=True).",
                     "Ts_Rank(close, 10)"),
            Operator("Ts_Delay", "TimeSeries", "Ts_Delay(x, d)",
                     "Value of x at d periods ago. "
                     "Formula: x[t-d].",
                     "Ts_Delay(close, 5)"),
            Operator("Ts_Delta", "TimeSeries", "Ts_Delta(x, d)",
                     "Difference between current x and x at d periods ago. "
                     "Formula: x[t] - x[t-d].",
                     "Ts_Delta(close, 1)"),
            Operator("Ts_Return", "TimeSeries", "Ts_Return(x, d)",
                     "Percentage change of x over d periods. "
                     "Formula: x[t] / x[t-d] - 1.",
                     "Ts_Return(close, 5)"),
            Operator("Ts_Sum", "TimeSeries", "Ts_Sum(x, d, min_periods=1)",
                     "Sum of x over the past d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: Σ_{i=0..d-1} x[t-i].",
                     "Ts_Sum(volume, 20)"),
            Operator("Ts_Mean", "TimeSeries", "Ts_Mean(x, d, min_periods=1)",
                     "Arithmetic mean of x over the past d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: (1/d) Σ_{i=0..d-1} x[t-i].",
                     "Ts_Mean(close, 20)"),
            Operator("Ts_Std", "TimeSeries", "Ts_Std(x, d, min_periods=1)",
                     "Sample standard deviation of x over the past d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: sqrt( (1/(d-1)) Σ (x_i - μ)² ).",
                     "Ts_Std(close, 20)"),
            Operator("Ts_Var", "TimeSeries", "Ts_Var(x, d, min_periods=1)",
                     "Sample variance of x over the past d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: (1/(d-1)) Σ (x_i - μ)².",
                     "Ts_Var(close, 20)"),
            Operator("Ts_Max", "TimeSeries", "Ts_Max(x, d, min_periods=1)",
                     "Maximum of x over the past d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: max(x[t-d+1:t]).",
                     "Ts_Max(high, 5)"),
            Operator("Ts_Min", "TimeSeries", "Ts_Min(x, d, min_periods=1)",
                     "Minimum of x over the past d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: min(x[t-d+1:t]).",
                     "Ts_Min(low, 5)"),
            Operator("Ts_Skewness", "TimeSeries", "Ts_Skewness(x, d, min_periods=1)",
                     "Skewness of x over the past d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: E[(x-μ)³] / σ³.",
                     "Ts_Skewness(close, 20)"),
            Operator("Ts_Kurtosis", "TimeSeries", "Ts_Kurtosis(x, d, min_periods=1)",
                     "Kurtosis of x over the past d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: E[(x-μ)⁴] / σ⁴ - 3.",
                     "Ts_Kurtosis(close, 20)"),
            Operator("Ts_ZScore", "TimeSeries", "Ts_ZScore(x, d, min_periods=1)",
                     "Z-score of current x relative to past d periods. "
                     "min_periods: min observations required, passed through to underlying Ts_Mean/Ts_Std (default 1). "
                     "Formula: (x[t] - μ_d) / (σ_d + 1e-12).",
                     "Ts_ZScore(close, 20)"),
            Operator("Ts_Correlation", "TimeSeries", "Ts_Correlation(x, y, d, min_periods=1)",
                     "Rolling Pearson correlation between x and y over d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: cov(x,y) / (σ_x σ_y).",
                     "Ts_Correlation(close, volume, 10)"),
            Operator("Ts_Covariance", "TimeSeries", "Ts_Covariance(x, y, d, min_periods=1)",
                     "Rolling covariance between x and y over d periods. "
                     "min_periods: min observations required, passed through to underlying operators (default 1). "
                     "Formula: corr(x,y) * σ_x * σ_y.",
                     "Ts_Covariance(close, volume, 10)"),
            Operator("Ts_Rsquare", "TimeSeries", "Ts_Rsquare(x, y, d, min_periods=1)",
                     "R-squared of linear regression of x on y over d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: corr(x,y)².",
                     "Ts_Rsquare(close, vwap, 20)"),
            Operator("Ts_Beta", "TimeSeries", "Ts_Beta(x, y, d, min_periods=1)",
                     "Regression beta of x on y over d periods. "
                     "min_periods: min observations required, passed through to underlying operators (default 1). "
                     "Formula: cov(x,y) / var(y).",
                     "Ts_Beta(returns, market_return, 60)"),
            Operator("Ts_Residual", "TimeSeries", "Ts_Residual(x, y, d, min_periods=1)",
                     "Residual of x after regressing on y over d periods. "
                     "min_periods: min observations required, passed through to underlying operators (default 1). "
                     "Formula: x - (α + β·y), where α = μ_x - β·μ_y.",
                     "Ts_Residual(close, vwap, 20)"),
            Operator("Ts_WMA", "TimeSeries", "Ts_WMA(x, d, min_periods=1)",
                     "Weighted moving average of x over d periods (linear weights). "
                     "min_periods: min observations required (default 1). "
                     "Formula: Σ_{i=1..d} i·x[t-d+i] / Σ i.",
                     "Ts_WMA(close, 10)"),
            Operator("Ts_EMA", "TimeSeries", "Ts_EMA(x, d, min_periods=1)",
                     "Exponential moving average with span = d. "
                     "min_periods: min observations required (default 1). "
                     "Formula: EMA_t = α·x_t + (1-α)·EMA_{t-1}, α = 2/(d+1).",
                     "Ts_EMA(close, 12)"),
            Operator("Ts_Median", "TimeSeries", "Ts_Median(x, d, min_periods=1)",
                     "Median of x over the past d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: median(x[t-d+1:t]).",
                     "Ts_Median(close, 20)"),
            Operator("Ts_MAD", "TimeSeries", "Ts_MAD(x, d, min_periods=1)",
                     "Mean absolute deviation from the median over d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: mean(|x - median(x)|).",
                     "Ts_MAD(close, 20)"),
            Operator("Ts_Quantile", "TimeSeries", "Ts_Quantile(x, d, q, min_periods=1)",
                     "q-th quantile of x over past d periods (q in [0,1]). "
                     "min_periods: min observations required (default 1). "
                     "Formula: quantile(x[t-d+1:t], q).",
                     "Ts_Quantile(close, 20, 0.75)"),
            Operator("Ts_CountNans", "TimeSeries", "Ts_CountNans(x, d, min_periods=1)",
                     "Count of NaN values in x over past d periods. "
                     "min_periods: min observations required (default 1). "
                     "Formula: count(isna(x[t-d+1:t])).",
                     "Ts_CountNans(close, 20)"),
            Operator("Ts_ArgMax", "TimeSeries", "Ts_ArgMax(x, d, min_periods=1)",
                     "Number of periods since the maximum of x over past d. "
                     "min_periods: min observations required (default 1). "
                     "Formula: d-1 - argmax(x[t-d+1:t]).",
                     "Ts_ArgMax(high, 20)"),
            Operator("Ts_ArgMin", "TimeSeries", "Ts_ArgMin(x, d, min_periods=1)",
                     "Number of periods since the minimum of x over past d. "
                     "min_periods: min observations required (default 1). "
                     "Formula: d-1 - argmin(x[t-d+1:t]).",
                     "Ts_ArgMin(low, 20)"),
            Operator("Ts_DecayLinear", "TimeSeries", "Ts_DecayLinear(x, d, min_periods=1)",
                     "Linearly decay-weighted average of x over d periods. "
                     "min_periods: min observations required (default 1). "
                     "Weights: [d, d-1, ..., 1] normalised.",
                     "Ts_DecayLinear(close, 10)"),
            Operator("Ts_DecayExp", "TimeSeries", "Ts_DecayExp(x, d, min_periods=1)",
                     "Exponentially decay-weighted average of x over d periods. "
                     "min_periods: min observations required (default 1). "
                     "Weights: exp(linspace(0,-1,d)) normalised.",
                     "Ts_DecayExp(close, 10)"),
        ]
        ops.extend(ts_ops)

        # ============================
        # 2. Cross-Sectional Operators (Cs_*)
        # ============================
        cs_ops = [
            Operator("Cs_Rank", "CrossSectional", "Cs_Rank(x)",
                     "Percentile rank of x across all assets at the same time step (1 = highest). "
                     "Formula: rank(x, axis=1) / (N-1).",
                     "Cs_Rank(close)"),
            Operator("Cs_ZScore", "CrossSectional", "Cs_ZScore(x)",
                     "Z-score of x across all assets at the same time step. "
                     "Formula: (x - μ_cs) / (σ_cs + 1e-12), where μ_cs = mean(axis=1), σ_cs = std(axis=1).",
                     "Cs_ZScore(close)"),
            Operator("Cs_Mean", "CrossSectional", "Cs_Mean(x)",
                     "Cross-sectional mean of x. Formula: mean(x, axis=1).",
                     "Cs_Mean(close)"),
            Operator("Cs_Std", "CrossSectional", "Cs_Std(x)",
                     "Cross-sectional standard deviation of x. Formula: std(x, axis=1).",
                     "Cs_Std(close)"),
            Operator("Cs_Sum", "CrossSectional", "Cs_Sum(x)",
                     "Cross-sectional sum of x. Formula: sum(x, axis=1).",
                     "Cs_Sum(volume)"),
            Operator("Cs_Median", "CrossSectional", "Cs_Median(x)",
                     "Cross-sectional median of x. Formula: median(x, axis=1).",
                     "Cs_Median(close)"),
            Operator("Cs_MAD", "CrossSectional", "Cs_MAD(x)",
                     "Cross-sectional mean absolute deviation from median. "
                     "Formula: mean(|x - median(x)|, axis=1).",
                     "Cs_MAD(close)"),
            Operator("Cs_Percentile", "CrossSectional", "Cs_Percentile(x)",
                     "Percentile rank of x across assets [0, 1]. Alias for Cs_Rank.",
                     "Cs_Percentile(close)"),
            Operator("Cs_Neutralize", "CrossSectional", "Cs_Neutralize(x, group)",
                     "Demean x within each group (e.g., industry). "
                     "Formula: x - mean(x, axis=1) (fallback when group map unavailable).",
                     "Cs_Neutralize(close, industry)"),
            Operator("Cs_Winsorize", "CrossSectional", "Cs_Winsorize(x, lower, upper)",
                     "Winsorize x at given percentile bounds per date. "
                     "Formula: clip(x, q_lower, q_upper).",
                     "Cs_Winsorize(close, 0.01, 0.99)"),
        ]
        ops.extend(cs_ops)

        # ============================
        # 3. Mathematical Operators
        # ============================
        math_ops = [
            Operator("Add", "Math", "Add(x, y)",
                     "Element-wise addition: x + y.",
                     "Add(close, open)"),
            Operator("Sub", "Math", "Sub(x, y)",
                     "Element-wise subtraction: x - y.",
                     "Sub(close, open)"),
            Operator("Mul", "Math", "Mul(x, y)",
                     "Element-wise multiplication: x * y.",
                     "Mul(close, volume)"),
            Operator("Div", "Math", "Div(x, y)",
                     "Element-wise safe division: x / y with y=0 guarded by 1e-12.",
                     "Div(close, vwap)"),
            Operator("Abs", "Math", "Abs(x)",
                     "Absolute value: |x|.",
                     "Abs(Sub(close, open))"),
            Operator("Sign", "Math", "Sign(x)",
                     "Sign of x: -1, 0, or 1.",
                     "Sign(Sub(close, open))"),
            Operator("Log", "Math", "Log(x)",
                     "Natural logarithm with safe guard: log(|x| + 1e-12).",
                     "Log(volume)"),
            Operator("Sqrt", "Math", "Sqrt(x)",
                     "Square root with safe guard: sqrt(|x|).",
                     "Sqrt(Abs(close))"),
            Operator("Exp", "Math", "Exp(x)",
                     "Exponential clipped to [-50,50] to avoid overflow.",
                     "Exp(Cs_ZScore(close))"),
            Operator("Power", "Math", "Power(x, n)",
                     "Raise x to the n-th power: xⁿ.",
                     "Power(Sub(close, open), 2)"),
            Operator("SignedPower", "Math", "SignedPower(x, n)",
                     "Sign-preserving power: sign(x) * |x|^n. "
                     "Compresses (<1) or expands (>1) magnitude while keeping original direction. "
                     "Formula: sign(x) * |x|^n.",
                     "SignedPower(returns, 0.5)"),
            Operator("Max", "Math", "Max(x, y)",
                     "Element-wise maximum: max(x, y).",
                     "Max(close, open)"),
            Operator("Min", "Math", "Min(x, y)",
                     "Element-wise minimum: min(x, y).",
                     "Min(close, open)"),
            Operator("Inverse", "Math", "Inverse(x)",
                     "Reciprocal with safe guard: 1 / (x + 1e·1_{x=0}).",
                     "Inverse(volume)"),
            Operator("Neg", "Math", "Neg(x)",
                     "Negation: -x.",
                     "Neg(close)"),
            Operator("Clip", "Math", "Clip(x, lower, upper)",
                     "Clip x to [lower, upper] bounds.",
                     "Clip(close, 0, 100)"),
        ]
        ops.extend(math_ops)

        # ============================
        # 4. Financial Raw Fields
        #    (match market-data parquet columns exactly)
        # ============================
        fin_ops = [
            # --- Price / OHLCV ---
            Operator("open", "Financial", "open",
                     "Opening price. Data field: open.",
                     "open"),
            Operator("close", "Financial", "close",
                     "Closing price. Data field: close.",
                     "close"),
            Operator("high", "Financial", "high",
                     "Highest price of the bar. Data field: high.",
                     "high"),
            Operator("low", "Financial", "low",
                     "Lowest price of the bar. Data field: low.",
                     "low"),
            Operator("pre_close", "Financial", "pre_close",
                     "Previous closing price. Data field: pre_close.",
                     "pre_close"),
            Operator("vwap", "Financial", "vwap",
                     "Volume-weighted average price. Data field: vwap.",
                     "vwap"),
            # --- Volume / Amount ---
            Operator("volume", "Financial", "volume",
                     "Trading volume. Data field: volume.",
                     "volume"),
            Operator("amt", "Financial", "amt",
                     "Dollar trading amount (成交额). Data field: amt.",
                     "amt"),
            # --- Return fields ---
            Operator("pct_chg", "Financial", "pct_chg",
                     "Period percentage change in percent, e.g. 10.0 means +10%. "
                     "Data field: pct_chg. For ChiNext/STAR this is pre-scaled by /2.",
                     "pct_chg"),
            Operator("Returns", "Financial", "Returns",
                     "Period return in decimal form: close / delay(close,1) - 1. Computed from close.",
                     "Returns"),
            Operator("change", "Financial", "change",
                     "Period price change amount (涨跌额): close - pre_close. "
                     "Computed from adjfactored + registered-corrected prices.",
                     "change"),
            # --- Turnover ---
            Operator("turn", "Financial", "turn",
                     "Turnover rate (换手率). Data field: turn.",
                     "turn"),
            # --- Daily point-in-time valuation ---
            Operator("pe", "Financial", "pe",
                     "Price/earnings ratio using the endpoint's current earnings basis. Data field: pe.",
                     "pe"),
            Operator("pe_ttm", "Financial", "pe_ttm",
                     "Trailing-twelve-month price/earnings ratio observable after date t close.",
                     "pe_ttm"),
            Operator("pb", "Financial", "pb",
                     "Price/book ratio observable after date t close.",
                     "pb"),
            Operator("ps", "Financial", "ps",
                     "Price/sales ratio. Data field: ps.",
                     "ps"),
            Operator("ps_ttm", "Financial", "ps_ttm",
                     "Trailing-twelve-month price/sales ratio observable after date t close.",
                     "ps_ttm"),
            Operator("dv_ratio", "Financial", "dv_ratio",
                     "Dividend yield in decimal form for the daily endpoint's stated basis.",
                     "dv_ratio"),
            Operator("dv_ttm", "Financial", "dv_ttm",
                     "Trailing-twelve-month dividend yield in decimal form.",
                     "dv_ttm"),
        ]
        ops.extend(fin_ops)

        # ============================
        # 5. Logical / Conditional Operators
        # ============================
        logic_ops = [
            Operator("If", "Logical", "If(condition, x, y)",
                     "Element-wise where: x where condition is True, else y. "
                     "Formula: x·1_{condition} + y·1_{¬condition}.",
                     "If(Greater(close, open), volume, 0)"),
            Operator("Greater", "Logical", "Greater(x, y)",
                     "Element-wise boolean: x > y.",
                     "Greater(close, open)"),
            Operator("Less", "Logical", "Less(x, y)",
                     "Element-wise boolean: x < y.",
                     "Less(close, open)"),
            Operator("Equal", "Logical", "Equal(x, y)",
                     "Element-wise boolean: x == y.",
                     "Equal(close, open)"),
            Operator("And", "Logical", "And(x, y)",
                     "Element-wise logical AND.",
                     "And(Greater(close, open), Greater(volume, Ts_Mean(volume,20)))"),
            Operator("Or", "Logical", "Or(x, y)",
                     "Element-wise logical OR.",
                     "Or(Greater(close, open), Greater(volume, Ts_Mean(volume,20)))"),
            Operator("Not", "Logical", "Not(x)",
                     "Element-wise logical NOT.",
                     "Not(Greater(close, open))"),
        ]
        ops.extend(logic_ops)

        # ============================
        # 6. Statistical / Composite
        # ============================
        stat_ops = [
            Operator("MACD", "Statistical", "MACD(x, fast, slow, signal)",
                     "MACD histogram line. "
                     "Formula: EMA_fast(x) - EMA_slow(x) - EMA_signal(EMA_fast - EMA_slow).",
                     "MACD(close, 12, 26, 9)"),
            Operator("RSI", "Statistical", "RSI(x, d)",
                     "Relative Strength Index over d periods. "
                     "Formula: 100 - 100 / (1 + avg_gain / avg_loss).",
                     "RSI(close, 14)"),
            Operator("BBands_Upper", "Statistical", "BBands_Upper(x, d, k)",
                     "Upper Bollinger Band. Formula: μ_d + k·σ_d.",
                     "BBands_Upper(close, 20, 2)"),
            Operator("BBands_Lower", "Statistical", "BBands_Lower(x, d, k)",
                     "Lower Bollinger Band. Formula: μ_d - k·σ_d.",
                     "BBands_Lower(close, 20, 2)"),
            Operator("VWAP_Deviation", "Statistical", "VWAP_Deviation(x)",
                     "Deviation from VWAP. Formula: x - vwap.",
                     "VWAP_Deviation(close)"),
            Operator("Price_Momentum", "Statistical", "Price_Momentum(d)",
                     "Cumulative return over d periods. Formula: close[t]/close[t-d] - 1.",
                     "Price_Momentum(20)"),
            Operator("Slope", "Statistical", "Slope(x, d)",
                     "Rolling linear regression slope of x on time over d periods. "
                     "Formula: β = cov(t, x) / var(t). "
                     "Positive slope = uptrend, negative = downtrend.",
                     "Slope(close, 24)"),
            Operator("Volatility_Ratio", "Statistical", "Volatility_Ratio(d_short, d_long)",
                     "Ratio of short-term to long-term volatility. "
                     "Formula: σ_short / σ_long.",
                     "Volatility_Ratio(5, 20)"),
            Operator("Trend_Strength", "Statistical", "Trend_Strength(x, d)",
                     "Absolute difference between EMA and SMA. "
                     "Formula: |EMA_d(x) - SMA_d(x)|.",
                     "Trend_Strength(close, 20)"),
        ]
        ops.extend(stat_ops)

        self._operators = ops

    @property
    def operators(self) -> typing.List[Operator]:
        """Return all operators in the library."""
        return self._operators

    @property
    def operator_names(self) -> typing.List[str]:
        """Return a list of all operator names."""
        return [op.name for op in self._operators]

    def get_by_category(self, category: str) -> typing.List[Operator]:
        """Return operators belonging to a specific category."""
        return [op for op in self._operators if op.category == category]

    def get_by_name(self, name: str) -> typing.Optional[Operator]:
        """Return an operator by its exact name."""
        for op in self._operators:
            if op.name == name:
                return op
        return None

    def format_for_llm(self) -> str:
        """Format the entire operator library as a prompt string for the LLM."""
        lines = [
            "=== OPERATOR LIBRARY (60+ Operators) ===",
            "",
            "You may ONLY use the following operators and raw fields to construct formulaic alpha factors.",
            "Each factor must be a valid, nested expression using these operators.",
            "All formulas are compiled into deterministic pandas/numpy code — precise arithmetic is guaranteed.",
            "",
        ]
        categories = {}
        for op in self._operators:
            categories.setdefault(op.category, []).append(op)

        for cat in sorted(categories.keys()):
            lines.append(f"--- {cat} ---")
            for op in categories[cat]:
                lines.append(f"  {op.signature}: {op.description}")
                if op.example:
                    lines.append(f"    Example: {op.example}")
            lines.append("")

        lines.append("=== END OF OPERATOR LIBRARY ===")
        return "\n".join(lines)

    def __len__(self) -> int:
        return len(self._operators)


# Global singleton instance
OPERATOR_LIBRARY = OperatorLibrary()
